version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Amitkumar@#18062001@#
      MYSQL_DATABASE: snit_website
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: snit_website
      DATABASE_USER: root
      DATABASE_PASSWORD: Amitkumar@#18062001@#
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DEBUG: "True"
